backend:
  name: github
  repo: yassine060793/NYK-Construction
  branch: main
  auth_endpoint: https://github.com/login/oauth/authorize

client_id: Ov23liXULp5aMe8osq27
site_url: https://nyk-construction.vercel.app

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "projects"
    label: "المشاريع"
    folder: "content/projects"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
  - name: "news"
    label: "الأخبار"
    folder: "content/news"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
